Update start_server

diff --git a/scripts/start_server b/scripts/start_server
--- a/scripts/start_server
+++ b/scripts/start_server
@@ -1,7 +1,7 @@
 #!/bin/bash
 service httpd start
 /tetetess.sh
-if [ $? -ne 0 ]; then
-  echo "faillure"
-fi
+# if [ $? -ne 0 ]; then
+#   echo "faillure"
+# fi
 
