Update start_server

diff --git a/scripts/start_server b/scripts/start_server
--- a/scripts/start_server
+++ b/scripts/start_server
@@ -1,8 +1,22 @@
 #!/bin/bash
 service httpd start
+
 /tetetess.sh
-if [ $? -ne 0 ]; then
-  echo "faillure"
-fi
-exit 0
+
+# TARGET_ID=$(aws deploy list-deployment-targets --deployment-id $DEPLOYMENT_ID  --region us-east-2  | jq .targetIds | sed 's/\"//g'| sed 's/\[//g' | sed 's/\]//g')
+
+# aws deploy batch-get-deployment-targets --deployment-id $DEPLOYMENT_ID --region us-east-2  --target-ids $TARGET_ID | grep -i scriptfailed 
+
+# if [ $(echo $?) -eq 0 ]; then
+
+# echo "codedeploy failed"
+
+# exit 1
+
+# else
+
+# echo "codedeploy success"
+
+# exit 0
+
 
