Update start_server

diff --git a/scripts/start_server b/scripts/start_server
--- a/scripts/start_server
+++ b/scripts/start_server
@@ -1,6 +1,7 @@
 #!/bin/bash
 service httpd start
-# if [ $? -ne 0 ]; then
-#   echo "faillure"
-# fi
+/tetetess.sh
+if [ $? -ne 0 ]; then
+  echo "faillure"
+fi
 
